# cloudbuild.yaml — React (CRA) → Cloud Run using Buildpacks, no Dockerfile

steps:
  # 1) Install deps (works even without package-lock.json)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--no-audit', '--no-fund']

  # 2) Build React app
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # 3) Build a container image with Buildpacks and push to Artifact Registry
  - name: 'gcr.io/buildpacks/pack'
    args:
      [
        'build',
        'asia-south1-docker.pkg.dev/$PROJECT_ID/web-containers/cocoma-digital:$SHORT_SHA',
        '--builder=gcr.io/buildpacks/builder',
        '--path=.',
        '--publish'
      ]

  # 4) Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run','deploy','cocoma-digital',
        '--image','asia-south1-docker.pkg.dev/$PROJECT_ID/web-containers/cocoma-digital:$SHORT_SHA',
        '--region','asia-south1',
        '--platform','managed',
        '--allow-unauthenticated',
        '--port','8080'
      ]

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/web-containers/cocoma-digital:$SHORT_SHA'
