substitutions:
  _REGION: "asia-south1"
  _REPO: "web-containers"
  _SERVICE: "cocoma-digital"

steps:
  # Build & push in one go with Kaniko (no Docker daemon)
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
      - --cache=true
      - --use-new-run
      - --snapshotMode=redo
      - --verbosity=info
    # If your Dockerfile is not at repo root, uncomment:
    # - --dockerfile=./Dockerfile
    # Add build args if needed:
    # - --build-arg=CI=true

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run","deploy","${_SERVICE}",
        "--image","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA",
        "--region","${_REGION}",
        "--platform","managed",
        "--allow-unauthenticated",
        "--port","8080"
      ]

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA"
